### ISSUE TITLE
Unable to make it work

### ISSUE THREAD

**Issue by vinayakg** [bridgecrewio/AirIAM#28]
I installed using below command and I am getting error as per snapshot

`pip3 install airiam --user`

Please share tips if you are able to make it work
I then tried `pip install requests==2.18.4` and it gave 

> ERROR: airiam 0.1.29 has requirement requests==2.23.0, but you'll have requests 2.18.4 which is incompatible
Python 3.7.7, pip 20.0.2 from /usr/local/lib/python3.7/site-packages/pip (python 3.7)
![image](https://user-images.githubusercontent.com/1701204/81323638-505c6680-90b3-11ea-8f96-e9d67657578a.png)

**Comment by nimrodkor** [comment]
Hi @vinayakg!
What this means is that you have a different version of the `requests` library. However, you may notice the last line in the screen shot says `Successfully installed airiam`!
That means you may run AirIAM. I make very simple use of the `requests` library so I expect AirIAM to work smoothly. If you still run into problems, let me know here!

**Comment by vinayakg** [comment]
Appreciate the quick response @nimrodkor 
I had posted this since the command was not recognized and was giving not found. After you responded, went ahead and on few searches figured that python is not in my path and hence pip packages were not found.
Ran the below command to fix
`export` PATH="/Users/<username>/Library/Python/3.7/bin:$PATH"

Hope this helps others as well :)

**Comment by vinayakg** [comment]
This has worked for me. Closing the issue for now
