### ISSUE TITLE
Error when executing airiam terraform cmd

### ISSUE THREAD

**Issue by ewahyudi** [bridgecrewio/AirIAM#30]
Hello,

I have installed airIAM on an AmzLinux2 EC2 instance.  Installation went through with no issues.  I was able to execute the 2 cmds, airiam -h & airiam find_unused just fine and returned the expected results.  When I tried to run the 'airiam terraform' cmd, I received the following error message:

![image](https://user-images.githubusercontent.com/67072053/84937580-fdaa9d00-b0a9-11ea-9a92-ee827b646149.png)

After reaching out for assistance via slack chat, I was advised to install terraform, and so I did.  I have installed terraform where its cmd is globally accessible; without having to cd into the dir where it's installed.  I have verified this by running **terraform -v** and this returned the terraform version with no issue.   Strangely enough, when I ran the **airiam terraform** cmd initially, that created the results dir and all of the .tf files but not the .tfstate

So I ran **airiam terraform** again, and I'm still receiving the same error (like the screen capture above).   Please provide some guidance. 

Python version: 3.7
Terraform v0.12.26
AirIAM version 0.1.31
Amazon Linux 2

Thank you,
Eri W.

**Comment by nimrodkor** [comment]
Hi @ewahyudi !

I've tried to reproduce this issue, and it seems you don't have terraform installed on that machine.
To install terraform, please follow this link:
https://learn.hashicorp.com/tutorials/terraform/install-cli
