### ISSUE TITLE
Question: support Roles of different accounts

### ISSUE THREAD

**Issue by mrudrara** [bridgecrewio/AirIAM#31]
Hi Team, 
wondering if AirIam find_unused resources support Roles or account ids for accessing different accounts. 
my company policy doesn't allow credentials in .aws/credentials file if I want to set up a single instance for all my environments

Thanks for your time

**Comment by nimrodkor** [comment]
Hi @mrudrara !

AirIAM supports environment variables too. I'm trying to understand your use case - you can specify a role to assume, but to assume it you will still need to have some kind of credentials locally - either in the credentials file or in the environment. Both are supported in AirIAM today.
So - how do you plan on assuming that role? You'll still need to authenticate with AWS before assuming that role.

Thanks!

**Comment by mrudrara** [comment]
Hi @nimrodkor 

Thanks for your valuable input.  I took assume role approach and it works as you suggested. Thanks again for prompt reply
