### ISSUE TITLE
Error running "airiam find_unused"

### ISSUE THREAD

**Issue by caiofattori-sec** [bridgecrewio/AirIAM#51]
$ airiam find_unused 

     ____      __           _____      ____     __        __
    / __ \    |__|  _  ____|_   _|    / __ \   |   \    /   |
   / /  \ \    __  | |/ ___| | |     / /  \ \  | |\ \  / /| |
  / /____\ \  |  | |   /     | |    / /____\ \ | | \ \/ / | |
 /  ______  \_|  |_|  |     _| |_  /  ______  \  |  \  /  | |
/_/        \_\_____|__|    |_____|/_/        \_\_|   \/   |_|
v0.1.44 

AirIAM - Least privilege AWS IAM Terraformer

To continuously scan configurations, try the Bridgecrew free community plan.
https://www.bridgecrew.io

INFO:botocore.credentials:Found credentials in environment variables.
Getting all IAM configurations for account xxxxxxxxxxxxx
Getting IAM credential report
Generated reports for all principals
Received usage results for all principals
Collecting password configurations for all IAM users in the account
Completed data collection, writing to local file...
Traceback (most recent call last):
  File "/usr/local/bin/airiam", line 5, in <module>
    run()
  File "/usr/local/Cellar/airiam/0.1.44/libexec/lib/python3.9/site-packages/airiam/main.py", line 29, in run
    runtime_results = find_unused(logger, args.profile, args.no_cache, args.last_used_threshold, args.command)
  File "/usr/local/Cellar/airiam/0.1.44/libexec/lib/python3.9/site-packages/airiam/find_unused/find_unused.py", line 51, in find_unused
    unused_active_access_keys, unused_console_login_profiles = find_unused_active_credentials(account_users, credential_report, unused_threshold)
  File "/usr/local/Cellar/airiam/0.1.44/libexec/lib/python3.9/site-packages/airiam/find_unused/find_unused.py", line 98, in find_unused_active_credentials
    credentials = next(creds for creds in credential_report if creds['user'] == user['UserName'])
StopIteration

**Comment by nimrodkor** [comment]
Hi @caiofattori-sec !
Thanks for reporting. It seems there is some misalignment between the responses airiam received from AWS. Does this reproduce consistently?
I will try to create a workaround.

**Comment by caiofattori-sec** [comment]
> Hi @caiofattori-sec !
> Thanks for reporting. It seems there is some misalignment between the responses airiam received from AWS. Does this reproduce consistently?
> I will try to create a workaround.

Hello, many thanks for feedback.
I did the test with other accounts with a smaller number of users and policies and the problem was not reproduced. But, in the account in which I reproduced the error, it happens every time.

**Comment by ankitsrao** [comment]
Hi @nimrodkor ,

I too faced the same issue.
Seems that when the number of IAM entities are large in number in an AWS account, this issue come up.

Thanks,
