### ISSUE TITLE
Enhancement: Auto-remediate

### ISSUE THREAD

**Issue by rdkls** [bridgecrewio/AirIAM#58]
Wondering if you guys were interested in ability to auto-remediate, that is auto-delete unused policies or roles?
Possibly with manual approval, or '-auto-approve' for all. I'm currently writing a bash script to do it, but could build in to AirIAM itself?

**Comment by rdkls** [comment]
I created a PR beginning this if you're interested, for now will just use on my own fork.
Thanks for a great tool, very useful.

**Comment by schosterbarak** [comment]
Hey @rdkls  thank you so much for this contribution. We aimed airiam to be a "read-only" tool and we do not want to introduce a remediation capability for it at the moment. I do suggest to run and maintain the remediation it as a supplement script with different access.

**Comment by rdkls** [comment]
Thanks for getting back to me @schosterbarak no problem, will close the PR
